name: Sync with Upstream

on:
  schedule:
    # Weekly on Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run mode'
        type: boolean
        default: false

jobs:
  sync-technical:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/kureyakey/zmk-config-zonkey.git
          git fetch upstream

      - name: Create branch
        run: |
          BRANCH="auto-sync-$(date +%Y%m%d)"
          git checkout -b $BRANCH
          echo "branch=$BRANCH" >> $GITHUB_ENV

      - name: Sync files
        run: |
          # Sync technical files only
          echo "Syncing dtsi files..."
          for file in config/boards/shields/zonkey/*.dtsi; do
            [ -f "$file" ] && git checkout upstream/main -- "$file" 2>/dev/null || true
          done

          echo "Syncing build files..."
          git checkout upstream/main -- config/west.yml 2>/dev/null || true
          git checkout upstream/main -- build.yaml 2>/dev/null || true

          # Sync base config from upstream
          echo "Syncing base config..."
          git show upstream/main:config/boards/shields/zonkey/zonkey_R.conf > config/boards/shields/zonkey/zonkey_R-base.conf 2>/dev/null || true

          # Preserve custom files
          echo "Preserving custom files..."
          git checkout HEAD -- config/zonkey.keymap 2>/dev/null || true
          git checkout HEAD -- config/zonkey-custom.dtsi 2>/dev/null || true
          git checkout HEAD -- config/boards/shields/zonkey/zonkey_R-custom.conf 2>/dev/null || true
          git checkout HEAD -- config/boards/shields/zonkey/zonkey_R.overlay 2>/dev/null || true

      - name: Merge configs
        run: |
          echo "Merging config files..."
          bash scripts/merge-configs.sh

      - name: Check changes
        id: changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected:"
            git diff --name-only
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes"
          fi

      - name: Commit
        if: steps.changes.outputs.has_changes == 'true' && inputs.dry_run != true
        run: |
          git add .
          git commit -m "chore: sync from upstream

          Files synced:
          $(git diff --name-only HEAD~1)"

          git push origin ${{ env.branch }}

      - name: Create PR
        if: steps.changes.outputs.has_changes == 'true' && inputs.dry_run != true
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ${{ env.branch }}
          delete-branch: true
          title: '[Auto] Sync from upstream'
          body: |
            ## Auto sync from upstream

            ### Synced ✅
            - Device tree files (*.dtsi)
            - Build configs

            ### Protected 🔒
            - Custom keymap
            - Custom settings

            ### Checklist
            - [ ] Build passes
            - [ ] Custom settings preserved
          labels: |
            upstream-sync
            automated
